language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer selfupdate
    - composer install --prefer-source --no-interaction

script:
    - phpunit

notifications:
    email: false
